### ISSUE TITLE
Compiler errors with ambiguous modules

### ISSUE THREAD

**Issue by tagsemb** [monadgroup/re19#1]
Hi, I'm trying to build the latest master, but I'm running into several compiler errors like these:

```
   Compiling engine v0.1.0 (D:\Code\github\re19\engine)
error[E0659]: `shader` is ambiguous (glob import vs glob import in the same module)
 --> engine\src\vertex_layout.rs:1:23
  |
1 | use crate::resources::shader::VertexShader;
  |                       ^^^^^^ ambiguous name
  |
note: `shader` could refer to the module imported here
 --> engine\src\resources.rs:2:9
  |
2 | pub use tool_resources::*;
  |         ^^^^^^^^^^^^^^^^^
  = help: consider adding an explicit import of `shader` to disambiguate
note: `shader` could also refer to the module imported here
 --> engine\src\resources.rs:5:9
  |
5 | pub use player_resources::*;
  |         ^^^^^^^^^^^^^^^^^^^
  = help: consider adding an explicit import of `shader` to disambiguate

```

Using rustc 1.57.0-nightly (aa7aca3b9 2021-09-30) as per the readme.

Any idea what I'm doing wrong?

**Comment by cpdt** [comment]
Hey @tagsemb, can you clarify what you're running to build it and from what directory? Just tested and I can still build it fine from the `tool` or `player` directories.

**Comment by tagsemb** [comment]
Hi, so sorry, it was just me being an idiot. I was trying to build from the repo root folder. Thank you for the quick reply, works fine once I did a double-take on the actual instructions!
